server:
  port: 8082

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin123}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidation12345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka